name: ${project.name}
main: me.hqm.plugindev.consolemobkill.CMKPlugin
version: ${project.version}
description: ${project.description}
author: HmmmQuestionMark
commands:
    mobkill:
        usage: /mobkill <type> [world]
        description: Kill mobs of a certain type.
    mobtypes:
        usage: /mobtypes
        description: Lists all the types of entities.